CREATE TABLE USERS(
id INT AUTO_INCREMENT PRIMARY KEY,
name_of_employee VARCHAR(100) NOT NULL,
PASSWORD_HASH VARCHAR(225) NOT NULL,
access_level  INT NOT NULL  CHECK (access_level BETWEEN 0 AND 5),
employment_status VARCHAR(20) DEFAULT 'active' CHECK (employment_status IN ('active', 'nonactive')),
employment_id VARCHAR(50) UNIQUE NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TERMINATED_AT TIMESTAMP NULL,
TITLE VARCHAR(100)
)